export const colorClasses: Record<
  string,
  { bg: string; text: string; ring: string; iconBg: string; bullet: string }
> = {
  blue: {
    bg: "bg-blue-50",
    text: "text-blue-700",
    ring: "ring-blue-200",
    iconBg: "bg-gradient-to-br from-blue-500 to-blue-600",
    bullet: "bg-blue-500",
  },
  green: {
    bg: "bg-green-50",
    text: "text-green-700",
    ring: "ring-green-200",
    iconBg: "bg-gradient-to-br from-green-500 to-green-600",
    bullet: "bg-green-500",
  },
  teal: {
    bg: "bg-teal-50",
    text: "text-teal-700",
    ring: "ring-teal-200",
    iconBg: "bg-gradient-to-br from-teal-500 to-teal-600",
    bullet: "bg-teal-500",
  },
  red: {
    bg: "bg-red-50",
    text: "text-red-700",
    ring: "ring-red-200",
    iconBg: "bg-gradient-to-br from-red-500 to-red-600",
    bullet: "bg-red-500",
  },
  purple: {
    bg: "bg-purple-50",
    text: "text-purple-700",
    ring: "ring-purple-200",
    iconBg: "bg-gradient-to-br from-purple-500 to-purple-600",
    bullet: "bg-purple-500",
  },
  indigo: {
    bg: "bg-indigo-50",
    text: "text-indigo-700",
    ring: "ring-indigo-200",
    iconBg: "bg-gradient-to-br from-indigo-500 to-indigo-600",
    bullet: "bg-indigo-500",
  },
  cyan: {
    bg: "bg-cyan-50",
    text: "text-cyan-700",
    ring: "ring-cyan-200",
    iconBg: "bg-gradient-to-br from-cyan-500 to-cyan-600",
    bullet: "bg-cyan-500",
  },
  amber: {
    bg: "bg-amber-50",
    text: "text-amber-700",
    ring: "ring-amber-200",
    iconBg: "bg-gradient-to-br from-amber-500 to-amber-600",
    bullet: "bg-amber-500",
  },
  orange: {
    bg: "bg-orange-50",
    text: "text-orange-700",
    ring: "ring-orange-200",
    iconBg: "bg-gradient-to-br from-orange-500 to-orange-600",
    bullet: "bg-orange-500",
  },
  slate: {
    bg: "bg-slate-50",
    text: "text-slate-700",
    ring: "ring-slate-200",
    iconBg: "bg-gradient-to-br from-slate-500 to-slate-600",
    bullet: "bg-slate-500",
  },
  emerald: {
    bg: "bg-emerald-50",
    text: "text-emerald-700",
    ring: "ring-emerald-200",
    iconBg: "bg-gradient-to-br from-emerald-500 to-emerald-600",
    bullet: "bg-emerald-500",
  },
};
